In [1]:
import pandas as pd

In [2]:
file_path = r"E:\AI_HUB\data\Other\메타데이터\tn_poi_master_POIMaster_all.csv"

tn_poi_master_POIMaster_all = pd.read_csv(file_path)

tn_poi_master_POIMaster_all

C:\Users\user\AppData\Local\Temp\ipykernel_5620\3884650053.py:3: DtypeWarning: Columns (3,4,12) have mixed types. Specify dtype option on import or set low_memory=False.
  tn_poi_master_POIMaster_all = pd.read_csv(file_path)

,POI_ID,POI_NM,BRNO,SGG_CD,ROAD_NM_ADDR,LOTNO_ADDR,ASORT_LCLASDC,ASORT_MLSFCDC,ASORT_SDASDC,X_COORD,Y_COORD,ROAD_NM_CD,LOTNO_CD
0,POI0100000000001X,장안평,,1123010600,NaN,서울특별시 동대문구 장안동 566 대,NaN,NaN,NaN,127.068515,37.563459,,1123010600105660000
1,POI0100000000002Y,육연평야,,4136025322,NaN,경기도 남양주시 진접읍 내각리 445-2답,NaN,NaN,NaN,127.168214,37.697096,,4136025322104450002
2,POI0100000000003Z,두평야,,4157025321,NaN,경기도 김포시 고촌읍 향산리 401 대,NaN,NaN,NaN,126.744188,37.624167,,4157025321104010000
3,POI01000000000040,우두평야,,4211011800,NaN,강원도 춘천시 우두동 1120 공,NaN,NaN,NaN,127.733450,37.910152,,4211011800111200000
4,POI01000000000051,예단평야,,4276033025,NaN,강원도 평창군 대화면 하안미리 1904답,NaN,NaN,NaN,128.431603,37.456985,,4276033025119040000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7442861,POI01000TR043516V,구례공영버스터미널,,,0,,NaN,NaN,NaN,127.468262,35.206690,,
7442862,POI01000TR043517V,갈매기대게도매집,,,경상북도 영덕군 강구면 영덕대게로 167,경북 영덕군 강구면 강구리 196-3,NaN,NaN,NaN,129.393847,36.363755,,
7442863,POI01000TR043518V,무드슈슈 워터룸,,,인천광역시 서구 이음1로 383,인천 서구 원당동,NaN,NaN,NaN,126.716801,37.594684,,
7442864,POI01000TR043519V,SK렌트카 차박2일,,,김녕해수욕장야영장,,NaN,NaN,NaN,127.716464,37.819459,,
7442865,POI01000TR043520V,GS25 안산중앙역점,,,경기도 안산시 단원구 민속공원로 98,경기 안산시 단원구 고잔동 747,NaN,NaN,NaN,126.839119,37.313933,,

In [11]:
# 도로명 주소에 "제주"  포함된 데이터 필터링
tn_poi_master_POIMaster_jeju = tn_poi_master_POIMaster_all[tn_poi_master_POIMaster_all['ROAD_NM_ADDR'].str.contains("제주", na=False)]

# 결과 저장
# jeju_file_path_by_address = '/mnt/data/jeju_poi_metadata_by_address.csv'
# jeju_data_by_address.to_csv(jeju_file_path_by_address, index=False)

tn_poi_master_POIMaster_jeju

,POI_ID,POI_NM,BRNO,SGG_CD,ROAD_NM_ADDR,LOTNO_ADDR,ASORT_LCLASDC,ASORT_MLSFCDC,ASORT_SDASDC,X_COORD,Y_COORD,ROAD_NM_CD,LOTNO_CD
240022,POI01000000668B3U,세인트스톤더부티크,,5011013700,제주특별자치도 제주시 신광로 91,제주특별자치도 제주시 연동 275대,NaN,NaN,NaN,126.490126,33.483943,5011013700102750000000001,5011013700102750000
240023,POI01000000668B4V,제주아이애,,5011031022,제주특별자치도 제주시 한경면 용당1길 24,제주특별자치도 제주시 한경면 용수리 1463-2 대,NaN,NaN,NaN,126.178456,33.334557,5011031022114630002000001,5011031022114630002
240024,POI01000000668B6X,무뚱하우스,,5011031021,제주특별자치도 제주시 한경면 중산간서로 3276-8,제주특별자치도 제주시 한경면 청수리 3388-7 대,NaN,NaN,NaN,126.238355,33.302863,5011031021133880007000001,5011031021133880007
240025,POI01000000668B7Y,제주중앙여고교다목적학습관,,5011010400,제주특별자치도 제주시 구남동5길 11,제주특별자치도 제주시 이도이동 1988-1 학,NaN,NaN,NaN,126.538946,33.490885,5011010400106120000046255,5011010400119880001
240026,POI01000000668BD4,더블루시티,,5011013700,제주특별자치도 제주시 제원1길 29,제주특별자치도 제주시 연동 251-22대,NaN,NaN,NaN,126.486302,33.489273,5011013700102510022000001,5011013700102510022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7442831,POI01000TR043484V,비욘드북카페,,,제주특별자치도 서귀포시 성산읍 신천동로 24-30,제주특별자치도 서귀포시 성산읍 신천리 538-2,NaN,NaN,NaN,126.854171,33.345066,,
7442835,POI01000TR043488V,제주김만복 함덕점,,,제주특별자치도 제주시 조천읍 함덕28길 1,제주특별자치도 제주시 조천읍 함덕리 4157-5,NaN,NaN,NaN,126.674835,33.537959,,
7442836,POI01000TR043489V,이디야커피 서귀포동홍점,,,제주특별자치도 서귀포시 동홍동로 9,제주특별자치도 서귀포시 동홍동 473-1,NaN,NaN,NaN,126.574725,33.255693,,
7442844,POI01000TR043498V,언더라운지 함덕점,,,제주특별자치도 제주시 조천읍 함덕로 40,제주특별자치도 제주시 조천읍 함덕리 산 14,NaN,NaN,NaN,126.671166,33.542414,,
7442852,POI01000TR043506V,낭구지횟집,,,제주특별자치도 서귀포시 표선면 민속해안로 585,제주특별자치도 서귀포시 표선면 표선리 40-35,NaN,NaN,NaN,126.843229,33.325059,,

In [12]:
tn_poi_master_POIMaster_jeju.isnull().sum()

POI_ID                0
POI_NM                0
BRNO                  0
SGG_CD                0
ROAD_NM_ADDR          0
LOTNO_ADDR            0
ASORT_LCLASDC    109761
ASORT_MLSFCDC    109761
ASORT_SDASDC     109761
X_COORD               0
Y_COORD               0
ROAD_NM_CD            0
LOTNO_CD              0
dtype: int64

In [13]:
columns_to_drop = ['BRNO', 'LOTNO_ADDR', 'ASORT_LCLASDC', 'ASORT_MLSFCDC', 'ASORT_SDASDC']

tn_poi_master_POIMaster_jeju = tn_poi_master_POIMaster_jeju.drop(columns=columns_to_drop)

# 결과 확인
tn_poi_master_POIMaster_jeju.isnull().sum()

POI_ID          0
POI_NM          0
SGG_CD          0
ROAD_NM_ADDR    0
X_COORD         0
Y_COORD         0
ROAD_NM_CD      0
LOTNO_CD        0
dtype: int64

In [14]:
tn_poi_master_POIMaster_jeju.head()

,POI_ID,POI_NM,SGG_CD,ROAD_NM_ADDR,X_COORD,Y_COORD,ROAD_NM_CD,LOTNO_CD
240022,POI01000000668B3U,세인트스톤더부티크,5011013700,제주특별자치도 제주시 신광로 91,126.490126,33.483943,5011013700102750000000001,5011013700102750000
240023,POI01000000668B4V,제주아이애,5011031022,제주특별자치도 제주시 한경면 용당1길 24,126.178456,33.334557,5011031022114630002000001,5011031022114630002
240024,POI01000000668B6X,무뚱하우스,5011031021,제주특별자치도 제주시 한경면 중산간서로 3276-8,126.238355,33.302863,5011031021133880007000001,5011031021133880007
240025,POI01000000668B7Y,제주중앙여고교다목적학습관,5011010400,제주특별자치도 제주시 구남동5길 11,126.538946,33.490885,5011010400106120000046255,5011010400119880001
240026,POI01000000668BD4,더블루시티,5011013700,제주특별자치도 제주시 제원1길 29,126.486302,33.489273,5011013700102510022000001,5011013700102510022

In [15]:
jeju_file_path_by_address = r"E:\AI_HUB\data\Other\메타데이터\tn_poi_master_POIMaster_all_jeju.csv"
tn_poi_master_POIMaster_jeju.to_csv(jeju_file_path_by_address, index=False)