In [1]:
import pandas as pd

In [2]:
file_path = r"E:\AI_HUB\data\Validation\labeled_data\VL_csv\tn_tour_photo_관광사진_H.csv"

tn_tour_photo = pd.read_csv(file_path)

tn_tour_photo

,TRAVEL_ID,VISIT_AREA_ID,TOUR_PHOTO_SEQ,PHOTO_FILE_ID,PHOTO_FILE_NM,PHOTO_FILE_FRMAT,PHOTO_FILE_DT,PHOTO_FILE_SAVE_PATH,PHOTO_FILE_RESOLUTION,PHOTO_FILE_X_COORD,PHOTO_FILE_Y_COORD,VISIT_AREA_NM
0,h_h000117,2305250004,0,h00011701099p0001,h00011701099p0001.jpg,jpg,2023-05-25 16:05:59,/photo/,4000x2252,126.408693,33.439146,NaN
1,h_h000063,2305270007,0,h00006301006p0001,h00006301006p0001.jpg,jpg,2023-05-27 15:50:01,/photo/,3024x3024,126.736425,33.280755,NaN
2,h_h000117,2305280004,0,h00011704005p0001,h00011704005p0001.jpg,jpg,2023-05-28 15:40:13,/photo/,4000x2252,126.534492,33.519250,NaN
3,h_h000153,2305290007,0,h00015302099p0001,h00015302099p0001.jpg,jpg,2023-05-29 18:16:19,/photo/,4032x2268,126.791128,33.304060,NaN
4,f_f001852,2305300003,0,f00185202004p0001,f00185202004p0001.jpg,jpg,2023-05-30 13:20:54,/photo/,4000x1848,128.952131,37.767080,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1834,h_h001249,2306270007,18,h00124903007p0019,h00124903007p0019.jpg,jpg,2023-06-27 16:43:15,/photo/,4032x3024,126.893394,33.415881,NaN
1835,h_h006641,2309170004,18,h00664101004p0019,h00664101004p0019.jpg,jpg,2023-09-17 18:09:03,/photo/,4032x3024,126.737097,33.555583,NaN
1836,h_h000299,2306060012,19,h00029901012p0020,h00029901012p0020.jpg,jpg,2023-06-06 15:15:39,/photo/,4000x3000,126.289733,33.205555,NaN
1837,h_h001249,2306250003,19,h00124901004p0020,h00124901004p0020.jpg,jpg,2023-06-25 22:31:45,/photo/,4032x3024,126.322878,33.254447,NaN
1838,h_h006660,2309160005,19,h00666001006p0020,h00666001006p0020.jpg,jpg,2023-09-16 15:35:34,/photo/,4032x3024,126.587106,33.523411,집

In [3]:
tn_tour_photo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1839 entries, 0 to 1838
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TRAVEL_ID              1839 non-null   object
 1   VISIT_AREA_ID          1839 non-null   int64
 2   TOUR_PHOTO_SEQ         1839 non-null   int64
 3   PHOTO_FILE_ID          1839 non-null   object
 4   PHOTO_FILE_NM          1839 non-null   object
 5   PHOTO_FILE_FRMAT       1839 non-null   object
 6   PHOTO_FILE_DT          1839 non-null   object
 7   PHOTO_FILE_SAVE_PATH   1839 non-null   object
 8   PHOTO_FILE_RESOLUTION  1839 non-null   object
 9   PHOTO_FILE_X_COORD     1839 non-null   float64
 10  PHOTO_FILE_Y_COORD     1839 non-null   float64
 11  VISIT_AREA_NM          984 non-null    object
dtypes: float64(2), int64(2), object(8)
memory usage: 172.5+ KB

In [4]:
# dtype 변환

tn_tour_photo['VISIT_AREA_ID'] = tn_tour_photo['VISIT_AREA_ID'].astype(str)
tn_tour_photo['PHOTO_FILE_DT'] = pd.to_datetime(tn_tour_photo['PHOTO_FILE_DT'])
tn_tour_photo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1839 entries, 0 to 1838
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TRAVEL_ID              1839 non-null   object
 1   VISIT_AREA_ID          1839 non-null   object
 2   TOUR_PHOTO_SEQ         1839 non-null   int64
 3   PHOTO_FILE_ID          1839 non-null   object
 4   PHOTO_FILE_NM          1839 non-null   object
 5   PHOTO_FILE_FRMAT       1839 non-null   object
 6   PHOTO_FILE_DT          1839 non-null   datetime64[ns]
 7   PHOTO_FILE_SAVE_PATH   1839 non-null   object
 8   PHOTO_FILE_RESOLUTION  1839 non-null   object
 9   PHOTO_FILE_X_COORD     1839 non-null   float64
 10  PHOTO_FILE_Y_COORD     1839 non-null   float64
 11  VISIT_AREA_NM          984 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 172.5+ KB

In [5]:
# 필요 없는 열 제거

columns_to_drop = ['PHOTO_FILE_ID', 'PHOTO_FILE_FRMAT', 'PHOTO_FILE_SAVE_PATH', 'VISIT_AREA_NM', "PHOTO_FILE_RESOLUTION", "TOUR_PHOTO_SEQ"]

tn_tour_photo = tn_tour_photo.drop(columns=columns_to_drop)
tn_tour_photo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1839 entries, 0 to 1838
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TRAVEL_ID           1839 non-null   object
 1   VISIT_AREA_ID       1839 non-null   object
 2   PHOTO_FILE_NM       1839 non-null   object
 3   PHOTO_FILE_DT       1839 non-null   datetime64[ns]
 4   PHOTO_FILE_X_COORD  1839 non-null   float64
 5   PHOTO_FILE_Y_COORD  1839 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 86.3+ KB

## 제주도만 필터링

In [6]:
# VISIT_AREA_NM을 알기 위해 병합 필요 -> tn_visit_area_info 테이블 불러오기(이미 제주도만 있음, 병합 안 되는 행은 삭제)

file_path = r"E:\AI_HUB\data\Validation\labeled_data\VL_csv\cleaned_data\tn_visit_area_info.csv"

tn_visit_area_info = pd.read_csv(file_path)
tn_visit_area_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2710 entries, 0 to 2709
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VISIT_AREA_ID        2710 non-null   int64
 1   TRAVEL_ID            2710 non-null   object
 2   VISIT_AREA_NM        2710 non-null   object
 3   VISIT_START_YMD      2710 non-null   object
 4   VISIT_END_YMD        2710 non-null   object
 5   ROAD_NM_ADDR         2710 non-null   object
 6   X_COORD              2710 non-null   float64
 7   Y_COORD              2710 non-null   float64
 8   RESIDENCE_TIME_MIN   2710 non-null   float64
 9   VISIT_AREA_TYPE_CD   2710 non-null   int64
 10  REVISIT_YN           2710 non-null   object
 11  VISIT_CHC_REASON_CD  2710 non-null   float64
 12  DGSTFN               2710 non-null   float64
 13  REVISIT_INTENTION    2710 non-null   float64
 14  RCMDTN_INTENTION     2710 non-null   float64
dtypes: float64(7), int64(2), object(6)
memory usage: 317.7+ KB

In [7]:
# 데이터 타입 변환
tn_visit_area_info['VISIT_AREA_ID'] = tn_visit_area_info['VISIT_AREA_ID'].astype(str)

In [8]:
print(tn_tour_photo['VISIT_AREA_ID'].apply(type).value_counts())
print(tn_visit_area_info['VISIT_AREA_ID'].apply(type).value_counts())

VISIT_AREA_ID
<class 'str'>    1839
Name: count, dtype: int64
VISIT_AREA_ID
<class 'str'>    2710
Name: count, dtype: int64

In [9]:
merged_data = pd.merge(tn_tour_photo, tn_visit_area_info, on='VISIT_AREA_ID', how='inner')

merged_data

,TRAVEL_ID_x,VISIT_AREA_ID,PHOTO_FILE_NM,PHOTO_FILE_DT,PHOTO_FILE_X_COORD,PHOTO_FILE_Y_COORD,TRAVEL_ID_y,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,X_COORD,Y_COORD,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION
0,h_h000063,2305270007,h00006301006p0001.jpg,2023-05-27 15:50:01,126.736425,33.280755,h_h000063,법련사,2023-05-27,2023-05-27,제주특별자치도 서귀포시 남원읍 남태해안로 319,126.736978,33.281210,30.0,2,N,11.0,3.0,2.0,2.0
1,h_h000063,2305270007,h00006301006p0001.jpg,2023-05-27 15:50:01,126.736425,33.280755,h_h000264,슈퍼마켓 화이트 버거 스탠드,2023-05-27,2023-05-27,제주특별자치도 제주시 한림읍 명월성로 141,126.263698,33.396355,30.0,11,N,2.0,5.0,5.0,5.0
2,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000063,서문 식당,2023-05-28,2023-05-28,제주특별자치도 서귀포시 표선면 성읍민속로 101,126.799009,33.386040,30.0,11,N,2.0,4.0,4.0,4.0
3,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000117,제주항 연안여객터미널,2023-05-28,2023-05-28,제주특별자치도 제주시 임항로 111,126.535003,33.519593,30.0,9,Y,8.0,4.0,4.0,4.0
4,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000153,퓨어 베 베,2023-05-28,2023-05-28,제주특별자치도 제주시 오라로 9,126.506694,33.499554,0.0,12,N,8.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6338,h_h001249,2306250003,h00124901004p0020.jpg,2023-06-25 22:31:45,126.322878,33.254447,h_h001552,오설록 티 뮤지엄,2023-06-25,2023-06-25,제주특별자치도 서귀포시 안덕면 신화역사로 15,126.289489,33.305913,60.0,2,Y,4.0,4.0,4.0,4.0
6339,h_h006660,2309160005,h00666001006p0020.jpg,2023-09-16 15:35:34,126.587106,33.523411,h_h006024,무민 랜드 제주,2023-09-16,2023-09-16,제주특별자치도 서귀포시 안덕면 병악로 420,126.381779,33.306616,60.0,3,N,1.0,4.0,4.0,4.0
6340,h_h006660,2309160005,h00666001006p0020.jpg,2023-09-16 15:35:34,126.587106,33.523411,h_h006639,신화 워터파크,2023-09-16,2023-09-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 38,126.315399,33.306074,180.0,6,N,2.0,4.0,4.0,4.0
6341,h_h006660,2309160005,h00666001006p0020.jpg,2023-09-16 15:35:34,126.587106,33.523411,h_h006654,인디언 서머,2023-09-16,2023-09-16,제주특별자치도 제주시 애월읍 애월로4길 9,126.315208,33.463338,120.0,11,N,5.0,5.0,5.0,5.0
6342,h_h006660,2309160005,h00666001006p0020.jpg,2023-09-16 15:35:34,126.587106,33.523411,h_h006660,제주 삼양동 유적,2023-09-16,2023-09-16,제주특별자치도 제주시 선사로2길 13,126.587681,33.523325,30.0,2,N,10.0,5.0,5.0,5.0

In [10]:
unique_count = tn_tour_photo['PHOTO_FILE_NM'].nunique()
total_count = tn_tour_photo['PHOTO_FILE_NM'].count()
print(f"Unique PHOTO_FILE_NM count: {unique_count}")
print(f"Total PHOTO_FILE_NM count: {total_count}")

# PHOTO_FILE_NM은 유일키다.

Unique PHOTO_FILE_NM count: 1839
Total PHOTO_FILE_NM count: 1839

In [11]:
# PHOTO_FILE_NM 컬럼의 고유값 개수
unique_photo_count = merged_data['PHOTO_FILE_NM'].nunique()
print(f"Unique PHOTO_FILE_NM count: {unique_photo_count}")

Unique PHOTO_FILE_NM count: 1669

In [12]:
# 고유한 PHOTO_FILE_NM만 추출, 중복된 행은 삭제

merged_data_unique = merged_data.drop_duplicates(subset=['PHOTO_FILE_NM'], keep='first')

In [13]:
# 필요한 열만 남겨서 저장
merged_data_cleaned = merged_data_unique[['VISIT_AREA_ID','VISIT_AREA_NM','PHOTO_FILE_NM', 'PHOTO_FILE_DT','PHOTO_FILE_X_COORD', 'PHOTO_FILE_Y_COORD']]

merged_data_cleaned

,VISIT_AREA_ID,VISIT_AREA_NM,PHOTO_FILE_NM,PHOTO_FILE_DT,PHOTO_FILE_X_COORD,PHOTO_FILE_Y_COORD
0,2305270007,법련사,h00006301006p0001.jpg,2023-05-27 15:50:01,126.736425,33.280755
2,2305280004,서문 식당,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250
8,2305290007,소노캄 제주,h00015302099p0001.jpg,2023-05-29 18:16:19,126.791128,33.304060
11,2305300003,오드란 베이커리,f00185202004p0001.jpg,2023-05-30 13:20:54,128.952131,37.767080
14,2305300005,비스타 케이 호텔 월드컵,f00201101004p0001.jpg,2023-05-30 20:56:47,128.528381,38.208119
...,...,...,...,...,...,...
6322,2307200007,제주 국제공항,h00239801007p0018.jpg,2023-07-20 16:17:39,124.609208,37.962464
6323,2306170003,교에 향,h00106002006p0019.jpg,2023-06-17 15:00:13,126.669906,33.426525
6328,2309170004,스타벅스 제주 용담 DT 점,h00664101004p0019.jpg,2023-09-17 18:09:03,126.737097,33.555583
6332,2306250003,제주 국제공항,h00124901004p0020.jpg,2023-06-25 22:31:45,126.322878,33.254447
6339,2309160005,무민 랜드 제주,h00666001006p0020.jpg,2023-09-16 15:35:34,126.587106,33.523411

새로운 곳 가보고 싶다는 게 압도적이니까^^ 통계자료로 썸ㄱ기

In [14]:
local_path = r"E:\AI_HUB\data\Validation\labeled_data\VL_csv\cleaned_data\tn_tour_photo_jeju_filtered.csv"
merged_data_cleaned.to_csv(local_path, index=False, encoding='utf-8-sig')

# 파일 저장 확인
print(f"로컬 경로에 파일 저장 완료: {local_path}")

로컬 경로에 파일 저장 완료: E:\AI_HUB\data\Validation\labeled_data\VL_csv\cleaned_data\tn_tour_photo_jeju_filtered.csv

In [1]:
import pandas as pd
import os

In [2]:
file_path = r'E:\AI_HUB\data\Validation\labeled_data\VL_csv\cleaned_data\tn_tour_photo_jeju_filtered.csv'

# 관광사진 테이블에서 제주도만 추출한 데이터 불러오기
tn_tour_photo_jeju_filtered = pd.read_csv(file_path)
tn_tour_photo_jeju_filtered.head()

,TRAVEL_ID_x,VISIT_AREA_ID,PHOTO_FILE_NM,PHOTO_FILE_DT,PHOTO_FILE_X_COORD,PHOTO_FILE_Y_COORD,TRAVEL_ID_y,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,X_COORD,Y_COORD,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION
0,h_h000063,2305270007,h00006301006p0001.jpg,2023-05-27 15:50:01,126.736425,33.280755,h_h000063,법련사,2023-05-27,2023-05-27,제주특별자치도 서귀포시 남원읍 남태해안로 319,126.736978,33.281210,30.0,2,N,11.0,3.0,2.0,2.0
1,h_h000063,2305270007,h00006301006p0001.jpg,2023-05-27 15:50:01,126.736425,33.280755,h_h000264,슈퍼마켓 화이트 버거 스탠드,2023-05-27,2023-05-27,제주특별자치도 제주시 한림읍 명월성로 141,126.263698,33.396355,30.0,11,N,2.0,5.0,5.0,5.0
2,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000063,서문 식당,2023-05-28,2023-05-28,제주특별자치도 서귀포시 표선면 성읍민속로 101,126.799009,33.386040,30.0,11,N,2.0,4.0,4.0,4.0
3,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000117,제주항 연안여객터미널,2023-05-28,2023-05-28,제주특별자치도 제주시 임항로 111,126.535003,33.519593,30.0,9,Y,8.0,4.0,4.0,4.0
4,h_h000117,2305280004,h00011704005p0001.jpg,2023-05-28 15:40:13,126.534492,33.519250,h_h000153,퓨어 베 베,2023-05-28,2023-05-28,제주특별자치도 제주시 오라로 9,126.506694,33.499554,0.0,12,N,8.0,4.0,4.0,4.0

In [4]:
# PHOTO_FILE_NM 리스트 생성
jeju_photo_names = tn_tour_photo_jeju_filtered['PHOTO_FILE_NM'].tolist()

# 원천 폴더 경로 지정 및 파일 목록 가져오기
jeju_raw_data = r"E:\AI_HUB\data\Validation\raw_data\VS_photo"
all_files_in_folder = os.listdir(jeju_raw_data)

# 삭제할 파일 리스트 생성 (경로를 문자열로 처리)
files_to_delete = [os.path.join(jeju_raw_data, file) for file in all_files_in_folder if file not in jeju_photo_names]

# 파일 삭제
for file_path in files_to_delete:
    try:
        os.remove(file_path)
        print(f"Deleted: {file_path}")
    except Exception as e:
        print(f"Error deleting {file_path}: {e}")

# 결과 확인
print(f"삭제된 파일 개수: {len(files_to_delete)}")

Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00149201009p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00149201009p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00466401004p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00575401003p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00575401003p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00466401002p0012.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00466401004p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00466401004p0015.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00525201003p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00466401002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00575401099p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501003p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401007p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00575401005p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01313501005p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401007p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501003p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00185201099p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501003p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00575401005p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401007p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401010p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00185201010p0013.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401010p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401010p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e00595401010p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01313501005p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01313501005p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501003p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501002p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00109101002p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501003p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\e01306501002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00185201009p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00208901012p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00208901012p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545901007p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625101007p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545901002p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545901002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545901007p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625102002p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625102002p0009.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545901099p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00217301099p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625101007p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625101007p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625102002p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00545902004p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00487402002p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00625102002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701011p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00712101012p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00019301099p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701011p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701011p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0010.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701011p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0009.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f00785701009p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00025701009p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497901007p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497902002p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f01056801002p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497901007p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00368002005p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701009p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701009p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00225001005p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00465901007p0009.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701009p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701009p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00011701003p0011.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701009p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00465901008p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f01056801002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00327701010p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497901007p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00025701010p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\f01056801002p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00465901008p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00368002005p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497901099p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00007203002p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00011701099p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\g00497901099p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00011701099p0013.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00007903006p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00011701099p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00011701002p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00029901012p0020.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00029901012p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00060701005p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00029901012p0017.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00070601009p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00070601009p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00070602006p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00088001011p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00088004006p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00172203010p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00124903007p0016.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00124903007p0019.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00124903007p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00124903007p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00124903007p0014.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00203202002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00183301012p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00205302013p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00203202002p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00248102002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00205302013p0012.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00245001007p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00205302013p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00205302013p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00239801006p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00245002002p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515402004p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515402004p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515403013p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515402003p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515403016p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515402004p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515402003p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00515403013p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00518901011p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00584303009p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00612401005p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00612401005p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00619801011p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00619801012p0006.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00620702002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00619801012p0011.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00619801012p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636402002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636401006p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00620702008p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636401012p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636401006p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00620702008p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636402002p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00645301007p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00620702002p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00633301099p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00620702006p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00645301007p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00645301007p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0008.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636702002p0005.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00636402002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00653501003p0001.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00653501003p0004.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00653501003p0002.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00653501003p0007.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00673101002p0003.jpg
Deleted: E:\AI_HUB\data\Validation\raw_data\VS_photo\h00673101002p0005.jpg
삭제된 파일 개수: 170